[package]
name = "battleisles"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.11.3"
hexx = "0.11"
bevy_panorbit_camera = "0.8.0"
serde = "1.0.190"
serde_json = "1.0.108"

[profile.dev.package."*"]
opt-level = 3