[package]
name = "battleisles"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.12.1"
bevy_pancam = "0.10"
hexx = "0.12.0"
serde = "1.0.190"
serde_json = "1.0.108"

[profile.dev.package."*"]
opt-level = 3