[package]
name = "battleisles"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "crates/battleisles_game",
    "editor",
]

[dependencies]
battleisles_game = { path = "crates/battleisles_game", version = "0.1.0" }

[profile.dev.package."*"]
opt-level = 3