[package]
name = "battleisles"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "crates/battleisles_bevy",
    "crates/battleisles_editor",
    "crates/battleisles_domain",
    "crates/battleisles_game",
    "editor",
]

[workspace.dependencies]
battleisles_bevy = { path = "crates/battleisles_bevy", version = "0.1.0" }
battleisles_domain = { path = "crates/battleisles_domain", version = "0.1.0" }
battleisles_editor = { path = "crates/battleisles_editor", version = "0.1.0" }
battleisles_game = { path = "crates/battleisles_game", version = "0.1.0" }
bevy = "0.19.1"
bevy_camera = "0.19.1"
bevy_color = "0.19.1"
bevy_egui = "0.42.0"
bevy_gizmos = "0.19.1"
getrandom = { version = "0.3", features = ["wasm_js"] }

[dependencies]
battleisles_domain = { workspace = true }
battleisles_game = { workspace = true }

[profile.dev.package."*"]
opt-level = 3
debug = false
