[package]
name = "battleisles_game"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.15.0"
bevy_egui = "0.31.1"
bevy_panorbit_camera = "0.20.1"
bevy_mod_raycast = "0.18.0"
serde = "1.0.190"
serde_json = "1.0.128"
