[package]
name = "battleisles_game"
version = "0.1.0"
edition = "2021"

[dependencies]
getrandom = { version = "0.3", features = ["wasm_js"] }
bevy = "=0.15.2"
bevy_egui = "0.33.0"
bevy_panorbit_camera = "0.25.0"
bevy_mod_raycast = "0.18.0"
serde = "1.0.190"
serde_json = "1.0.128"
