[package]
name = "battleisles_game"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.14.2"
bevy_egui = "0.29"
bevy_pancam = "0.14.0"
hexx = "0.18.0"
serde = "1.0.190"
serde_json = "1.0.128"
