name: Build and Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    container:
      image: fritzoid/rust-bevy-builder:latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build debug
      run: cargo build --verbose --workspace

    - name: Run tests debug
      run: cargo test --verbose --workspace
    
    - name: Build release
      run: cargo build --release --verbose --workspace 

    - name: Run tests release
      run: cargo test --release --verbose --workspace